name = "backtrace_details"
short_description= "Pairs a Ruby backtrace with the corresponding lines of code"
description="""
Ruby development involves looking at a lot of backtraces. Knowing that
something happend on line 15 isn't generally very helpful
becaues you don't know what's on line 15.

Pipe your ruby backtraces through `backtrace_details` and it'll
highlight the backtrace line, extract the trailing information on it,
_and_ tell you what was on the line in question.
"""
usage_command="backtrace_details -h"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""
type="executable"
language="bash"
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/backtrace_details"
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["ruby", "debugging"]
# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
