name = "blankless"
short_description= "converts whitespace-only lines to empty lines & optionally deletes."
description="""
When processing text in unix pipelines, you sometimes want to take lines that consist
entirely of whitespace characters and trim them. Sometimes you want to delete them
and their 0 length bretheren. Just add this into your pipeline and it'll take
care of that for you.
"""
# usage_command=""
fallback_usage="""
USAGE: no direct invocation. just pipe files into this.
       -d delete blank lines

       Ex.: cat foo.txt | blankless
            cat foo.txt | blankless -d
"""
type="executable"
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/blankless"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["text"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
