# the name of the command or function you're documenting
name="color-picker"
# a short (one line) description of what it does
short_description="Launches a color picker that returns a hex code"
description="""
macOS only: Launches a GUI color picker, waits for the user to choose
a color, and then outputs the corresponding hex color.

Note: if the user clicks cancel instead of choosing a color it'll
return `#ffaabb`
"""
# if the tool has some sort of usage / help documentation you can
# invoke, enter it in the usage_command. Otherwise, comment that out,
# and document it in the fallback_usage. In TOML you can create a
# multiline string by surrounding it with triple double quotes.
# """ like this """
# usage_command=""
fallback_usage="""
USAGE: color-picker
       Launches a system color picker and waits for the user
       to choose a color. Then returns the corresponding hex code.
       If you click cancel it'll output #ffaabb for... reasons."""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="ruby"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/color-picker"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi"
tags=["gui", "macos", "ruby"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
