# a template for `clu` toml files
name = "color_test"
short_description= "outputs a smooth gradient band along the RGB spectrum"
description="""
Use color_test to test the color rendering in your terminal. Will
display three smooth gradients of color in terminals with support for
high color fidelity.
"""
# usage_command=""
fallback_usage="""
USAGE: color_test
       takes no input. Just outputs the color band."""
type="executable"
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/color_test"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["color", "escape", "codes", "test", "ansi"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
