# a template for `clu` toml files


# the name of the command or function you're documenting
name="color-capture"
# a short (one line) description of what it does
short_description="Allows you to pipe a script without having its color escape codes stripped"
description="""
Unix pipes got you down? Stripping the color from your output? Run
them with color-capture and their glorious escape codes will be
preserved for the next tool in the chain.
"""
usage_command="color-capture"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/color-capture"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi"
tags=["escape", "codes", "ansii", "color"]
# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
