# the name of the command or function you're documenting
name="commands"
# a short (one line) description of what it does
short_description="Lists all the executables in your PATH"
description="""
Need a list of all the executables in your `$PATH`? I did.
`commands` will return a sorted list of executables found
in the directories in your `$PATH`. This is going to be long.
On my system it's ~3,500 lines.

Note: generally you're better off just calling `which <command>`
or `command -v <command>` to see if a specific command is
avaliable.
"""

# usage_command=""
fallback_usage="""
USAGE: commands
       Lists all the executables in your PATH"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/commands"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi"
tags=["search"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
