# Clu documentation file. Details: https://github.com/masukomi/Clu

# The name of the command or function you're documenting
# This is the thing you type to invoke it. Note: git scripts
# are typically named git-foo but you invoke them as 'git foo'.
# It's your call, but for these I'd recommend using git-foo in
# the name field. This will enable Clu to tell you where it's
# located on your system.
name="doom"
# a short (one line) description of what it does
short_description="a simple emacs launch helper"

# an optional detailed description of what it does.
# definitely include this if you're going to generate a web site.
# Note: You can include markdown in this and have it rendered
# when the web site is generated
#
description="""
doom (as in doom emacs) is a little utility to open a file in Emacs.
Specify `-n` to open the file in a new window (a "frame" in emacs-speak)

It will launch Emacs as a server, and always reconnect to the server
so that you can have near-instant launch times (after the 1st one).

If it reports problems run it with `-d` to see what Emacs was
complaining about. If there isn't an Emacs window open I'll usually
just run it with `-f` to force kill the emacs server and start a new
one rather than debugging the problem.
"""

# If the tool has some sort of usage / help documentation you can
# invoke, enter it in the usage_command. Otherwise, comment that out,
# and document it in the fallback_usage. In TOML you can create a
# multiline string by surrounding it with triple double quotes.
# """ like this """
usage_command="doom -h"

# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="zsh"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/doom"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

# additional keywords that might help you find this in a search
# or when browsing by tag. There are more features coming that
# will add functionality based on tags. ;)
#
tags=[ "emacs" ]
