# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="edit"
short_description="allows editing of files with ruby <path>:<line_no> style input"

description="""
enables you to just copy-paste lines from your backtrace and open in
your editor without having to remove the :line number and re-add it in 
whatever fashion your editor wants.
"""

usage_command="edit <path>[:<line_no>]"

# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/edit"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs/"

# can this be included in exports like the static blog generation
exportable=true

tags=[ "vim", "emacs"  ]
