# Clu documentation file. Details: https://github.com/masukomi/Clu

# The name of the command or function you're documenting
# This is the thing you type to invoke it. Note: git scripts
# are typically named git-foo but you invoke them as 'git foo'.
# It's your call, but for these I'd recommend using git-foo in
# the name field. This will enable Clu to tell you where it's
# located on your system.
name="fingerprints"
# a short (one line) description of what it does
short_description="outputs the fingerprints for all your public ssh keys"

# an optional detailed description of what it does.
# definitely include this if you're going to generate a web site.
# Note: You can include markdown in this and have it rendered
# when the web site is generated
#
description="""
Sometimes you need to know the fingerprints of one of your SSH keys.

I can never remember the invocation. This will show the name of the
public key and the fingerprint of it for comparison or sharing.

Prerequisets: `ssh-keygen` which you already have if you've generated
ssh keys.
"""

# If the tool has some sort of usage / help documentation you can
# invoke, enter it in the usage_command. Otherwise, comment that out,
# and document it in the fallback_usage. In TOML you can create a
# multiline string by surrounding it with triple double quotes.
# """ like this """
# usage_command=""

fallback_usage="""
USAGE: fingerprints
       That's it. Takes no args. Has no help.
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/fingerprints"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

# additional keywords that might help you find this in a search
# or when browsing by tag. There are more features coming that
# will add functionality based on tags. ;)
#
tags=[ "ssh", "security", "encryption", "keys"  ]
