# Clu documentation file. Details: https://github.com/masukomi/Clu

# The name of the command or function you're documenting
# This is the thing you type to invoke it. Note: git scripts
# are typically named git-foo but you invoke them as 'git foo'.
# It's your call, but for these I'd recommend using git-foo in
# the name field. This will enable Clu to tell you where it's
# located on your system.
name="format_sql"
# a short (one line) description of what it does
short_description="replaces the contents of a SQL file with a formatted version"

# an optional detailed description of what it does.
# definitely include this if you're going to generate a web site.
# Note: You can include markdown in this and have it rendered
# when the web site is generated
#
description="""
Nicely formats a SQL file for you.

Warning: will probably wreak havoc if run on anything that _isn't_ a
pure SQL file. That is to say, don't pass it a Python file with some
SQL mixed in. SQL files only.


Prerequisites: sqlformat executable which comes from the
[sqlparse](https://github.com/andialbrecht/sqlparse) Python library.
Install it with `pip3 install sqlparse`
"""

# If the tool has some sort of usage / help documentation you can
# invoke, enter it in the usage_command. Otherwise, comment that out,
# and document it in the fallback_usage. In TOML you can create a
# multiline string by surrounding it with triple double quotes.
# """ like this """
usage_command="format_sql"

# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/format_sql"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs/blob/master/bin/format_sql"

# additional keywords that might help you find this in a search
# or when browsing by tag. There are more features coming that
# will add functionality based on tags. ;)
#
tags=[ "sql", "formatting", "beautification"  ]
