# the name of the command or function you're documenting
name="gdef"
# a short (one line) description of what it does
short_description="Finds the definition of a Ruby, Crystal, or Elixir function"
description="""
`gdef` helps you `grep` for the "`def`inition" of a method in one of the
aforementioned languages.

Can handle the fact that sometimes a ruby method is defined as `def foo` and
sometimes it's `def self.foo` Either way it'll find it.
"""
usage_command="gdef"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/gdef"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi"
tags=["ruby", "crystal", "elixir", "search"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
