# a template for `clu` toml files


# the name of the command or function you're documenting
name="hr"
# a short (one line) description of what it does
short_description="outputs a horizontal rule the width of your terminal"
description="""
a silly little utility that draws a horizontal rule the full width
of your terminal.

Not very useful by itself, but nice to call from other scripts
when you need to divide some information visually.

By default it'll use Box Drawings Light Horizontal (\\u2500) for
a nice smooth line, but you can pass it any character you want and
it'll use that instead. Want a line of hearts? `hr ❤️`

Note: emojis end up a little weird because they're frequently more
than one character wide but your terminal expects monospaced
characters. 🤷‍♀️ Whatever. Experiment. Have fun.
"""
# usage_command=""
fallback_usage="""
USAGE: hr [character]
       If you pass it a character it will use that character to create
       the horizontal rule.
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/hr"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs/"
tags=["misc", "tui"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
