# a template for `clu` toml files
# the name of the command or function you're documenting
name="is_brewed"
# a short (one line) description of what it does
short_description="indicates if a package is installed via homebrew"
description="""
a simply utility to call to determine if something is already
installed via homebrew.

I use this in conjunction with [yadm](https://yadm.io/) to make my
bootstrap scripts idempotent.
"""
usage_command="is_brewed"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/is_brewed"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["homebrew", "search"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
