# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="manfile"
short_description="generate and / open an html version of a man page"

description="""
Generates an HTML version of the manpage
and optionally opens it in your browser.

Requires gum & pandoc
"""

usage_command="manfile"

fallback_usage="""
USAGE: manfile <manpage name>
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/manfile"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

# can this be included in exports like the static blog generation
exportable=true

# tags=[   ]
