# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="podcast_downloader"
short_description="lists episodes of a podcast and downloads one"

description="""
Used to download a specific episode from a podcast's RSS 
or ATOM feed. 
 
Doesn't have edge case handling for web pages that 
fail to link to their podcasts correctly, or podcasts
feed files that fail to link to their downloadable 
media correctly.

Creates a new file with current timestamp + episode title 
as its name.

PREREQUISITES:
- rss gem
"""

usage_command="podcast_downloader"

# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="ruby"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/podcast_downloader"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs/"

# can this be included in exports like the static blog generation
exportable=true

tags=[ "audio"  ]
