# a template for `clu` toml files


# the name of the command or function you're documenting
name="pr-age"
# a short (one line) description of what it does
short_description="outputs the age of a PR in days"
description="""
Wondering how old that PR is?

Run this from the repo that has the PR you're wondering about and
it'll tell you how old it is in days.

Prerequisites: [gh](https://github.com/cli/cli) - the official GitHub
command line client.
"""
usage_command="pr-age"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="ruby"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/pr-age"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["github", "git", "reporting"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
