# Clu documentation file. Details: https://github.com/masukomi/Clu

# the name of the command or function you're documenting
name="prep-itsalive"
# a short (one line) description of what it does
short_description="preps a template for an itsalive recording of the specified command"
description="""
Sets up a template to prep recording sessions that use itsalive and
asciinema.

See [this
post](https://weblog.masukomi.org/2022/10/11/recording_and_sharing_terminal_sessions/)
for details and links.
"""
usage_command="prep-itsalive"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/prep-itsalive"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
# additional keywords that might help you find this in a search
# or when browsing by tag
# future functionality: https://github.com/masukomi/Clu/issues/10
tags=[ "asciicast", "documentation", "recording" ]

# [[cheats]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
