# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="resize-img"
short_description="image resizer shorthand"

description="""
utilizes ImageMagick's `convert` command to resize the image
proportionally such that the longest dimension is no longer than those
supplied.

if you give it a dimension of 300x300 it'll downsize proportionally so
that the longest edge is 300 pixels.
"""

usage_command="resize-img"

# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/resize-img"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs/"

tags=[ "images"  ]
