# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="template_commenter"
short_description="adds comments to start & end of .haml, .rhtml, & .erb files"

description="""
Adds comments to the beginning and end of template files so that
you can easily tell which template generated which bit of the page
after they've been mushed together by your web framework.

Note: for Rails you can probably just use the
[noisy_partials](https://github.com/gwshaw/noisy_partials) gem.

Prerequisites: Ruby
"""

usage_command="template_commenter"

# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="ruby"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/template_commenter"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

tags=[ "ruby", "rails", "sinatra", "html", "templating"  ]
