# Clu documentation file. Details: https://github.com/masukomi/Clu

# the name of the command or function you're documenting
name="unbak"
# a short (one line) description of what it does
short_description="removes .bak from a file's name"

# an optional detailed description of what it does.
# definitely include this if you're going to generate a web site
#
description="""
A pair to the `bak` command. Takes a given file and removes the
trailing .bak from it's name.

Back things up with `bak` and restore them with `unbak`

(see also `bak`)
"""

# if the tool has some sort of usage / help documentation you can
# invoke, enter it in the usage_command. Otherwise, comment that out,
# and document it in the fallback_usage. In TOML you can create a
# multiline string by surrounding it with triple double quotes.
# """ like this """
usage_command="unbak"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/unbak"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
# additional keywords that might help you find this in a search
# or when browsing by tag
# tags=[  ];

# [[cheats]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
