# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="url2png"
short_description="uses Chrome to screenshot an URL"

description="""
Assumes you have Google Chrome installed, and runs it in headless mode
to screenshot the URL you pass it.

Note that this can be run while Chrome is loaded in your GUI
and will run without any of your plugins.

Note that the Firefox equivalent of this can not be run while
the GUI is loaded.
"""

usage_command="url2png"

# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/url2png"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

exportable=true

tags=[ "images", "screenshots", "web"  ]
