# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="vtt2txt"
short_description="converts vtt (video text tracks) to plaintext"

description="""
converts the .vtt files used for YouTube subtitles and whisper
transcriptions to text files.
"""

# usage_command=""

fallback_usage="""
USAGE: vtt2text path/to/file.vtt
       creates a new file in the same directory with 
       the same name but .vtt is swapped for .txt
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="python"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/vtt2txt"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

# can this be included in exports like the static blog generation
exportable=false

tags=[   ]
