# a template for `clu` toml files
# the name of the command or function you're documenting
name="watch_when"
# a short (one line) description of what it does
short_description="Polls a command and reports when its output changes"
usage_command="watch_when"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""
type="executable"
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/watch_when"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["debugging", "monitoring"]
# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
