# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - triggers:
    - ":jocat"
    - ":ilikegirls"
    replace: "[I Like Girls](https://youtu.be/Y2Y5KVtU810) - JoCat"

  - trigger: ":betalink"
    replace: "https://weblog.masukomi.org/2025/08/17/looking-for-beta-readers/"

  - trigger: ":warning"
    replace: "⚠️"

  - trigger: ":checked"
    replace: "✅"

  - triggers:
    - ":nocheck"
    - ":negacheck"
    replace: "❎"

  - trigger: ":unchecked"
    replace: "🟨"

  # uncommon characters
  - trigger: ":..."
    replace: "…"
  - trigger: ":?!"
    replace: "‽"
  - triggers:
    - ":zws"
    - ":zero-width-space"
    replace: "​"

  # Fractions
  - trigger: ":1/10"
    replace: "⅒"
  - trigger: ":1/9"
    replace: "⅑"
  - trigger: ":1/8"
    replace: "⅛"
  - trigger: ":1/7"
    replace: "⅐"
  - trigger: ":1/6"
    replace: "⅙"
  - trigger: ":1/5"
    replace: "⅙"
  - trigger: ":1/4"
    replace: "¼"
  - trigger: ":1/3"
    replace: "⅓"
  - trigger: ":1/2"
    replace: "½"
  - trigger: ":2/3"
    replace: "⅔"
  - trigger: ":3/4"
    replace: "¾"

  # Ordinal Indicators
  - trigger: ":nst"
    replace: "ˢᵗ"
  - trigger: ":nnd"
    replace: "ⁿᵈ"
  - trigger: ":nrd"
    replace: "ʳᵈ"
  - trigger: ":nth"
    replace: "ᵗʰ"


  # Mathy Things
  - trigger: ":>="
    replace: "≥"
  - trigger: ":<="
    replace: "≤"
  - trigger: ":chevron"
    replace: "»"
  - trigger: ":right-chevron"
    replace: "»"
  - trigger: ":left-chevron"
    replace: "«"
  - trigger: ":>>"
    replace: "»"
  - trigger: ":<<"
    replace: "«"
  - trigger: ":deg"
    replace: "°"

  # Arrow-ish things
  - trigger: ":right-angle"
    replace: "›"
  - trigger: ":left-angle"
    replace: "‹"
  - trigger: ":->"
    replace: "→"
  - trigger: ":<-"
    replace: "←"
  - triggers:
    - ":clockwise"
    - ":deosil"
    replace: "↻"
  - triggers:
    - ":counter-clockwise"
    - ":anti-clockwise"
    - ":widdershins"
    replace: "↺"

  # Esperanto Stuff
  # - lower case
  - trigger: ":cx"
    replace: "ĉ"
  - trigger: ":gx"
    replace: "ĝ"
  - trigger: ":hx"
    replace: "ĥ"
  - trigger: ":jx"
    replace: "ĵ"
  - trigger: ":sx"
    replace: "ŝ"
  - trigger: ":ux"
    replace: "ŭ"
  # - upper case
  - trigger: ":CX"
    replace: "Ĉ"
  - trigger: ":GX"
    replace: "Ĝ"
  - trigger: ":HX"
    replace: "Ĥ"
  - trigger: ":JX"
    replace: "Ĵ"
  - trigger: ":SX"
    replace: "Ŝ"
  - trigger: ":UX"
    replace: "Ŭ"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Random crap from writing
  - triggers:
    - "blaithin"
    - "Blaithin"
    - "blathin"
    replace: "Bláithín"
  - trigger: "fiance"
    replace: "fiancé"
  # And much more! For more information, visit the docs: https://espanso.org/docs/
