# the name of the command or function you're documenting
name="git-branchdate"
# a short (one line) description of what it does
short_description="Lists the date of the last commit of each branch"
description="""
Useful when trying to find branch that you edited in a specific
time-frame. E.g. "I know i was working on it 2 weeks ago..."

```text
❯ git branchdate
2022-10-16 00:07:58   asciinema
2022-10-12 00:02:52   beautification
2022-10-05 21:39:08   main
2022-11-11 15:45:14   markdown
2022-11-06 18:26:39   prettier_tables
2022-11-06 10:57:58   tags
2022-11-06 18:26:39   v2_staging
```
"""
# usage_command=""
fallback_usage="""
USAGE: git branchdate
       Lists the date of the last commit of each branch."""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-branchdate"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["git", "maintenance"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
