# the name of the command or function you're documenting
name="git-brv"
# a short (one line) description of what it does
short_description="A sorted prettier git branch -vv"
description="""
A compact, colorful, summary of your git branches.
"""
# usage_command=""
fallback_usage="""
USAGE: git brv
       Outputs a list of branches, sorted by date
       Example:
        ❯ git brv
        2022-11-11 markdown        origin/markdown   0d71347 strips ANSI escape codes in usage section
        2022-11-06 v2_staging      origin/v2_staging cbb273c updated output with Prettier::Table
        2022-11-06 prettier_tables                   cbb273c updated output with Prettier::Table
        2022-11-06 tags            origin/tags       1650dbf added tag support and tests
        2022-10-16 asciinema       origin/asciinema  b40d75b improved documentation
        2022-10-12 beautification                    f60726c added comment about box drawing characters
        2022-10-05 main            origin/main       0d2df47 added repo to meta6
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-brv"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi"
tags=["git"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
