# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="git-pick-divergent-names"
short_description="facilitates cherry-picking commits where merging would cause dupes"

description="""
If you've forked branch_b off of branch_a and then you rebase 
branch_a then you can't merge branch_b or you'll have tons of dupe
no-op commits.

This solves that problem by looking through recent commits 
(defaults to the past 50) looking for commits in a specified branch
whose titles do NOT appear in the current branch. If it finds
any it'll ask if you want to cherry-pick them into the current
branch. Works from oldest to newest.

Pre-requisites:
* `git curent-branch` should work
* sd should be installed
"""

usage_command="git-pick-divergent-names"

# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="ruby"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-pick-divergent-names"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

# can this be included in exports like the static blog generation
exportable=true

tags=[ "git"  ]
