# the name of the command or function you're documenting
name="git-find-twins"
# a short (one line) description of what it does
short_description="Finds other git branches whose HEADs point to the same"
description="""
It's possible to end up with multiple branches pointing to the same
[treeish](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftree-ishatree-ishalsotreeish). This makes it easy to find.

Checkout the branch you're looking for the twin of, then run
`git find-twins`

"""
#usage_command=""
fallback_usage="""
USAGE: git find-twins
       looks for other git branches with heads pointing
       to the same treeish as the current branch
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-find-twins"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["git", "search", "maintenance"]
# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
