# a template for `clu` toml files


# the name of the command or function you're documenting
name="git-ammender"
# a short (one line) description of what it does
short_description="adds changed files to last commit, and force pushes with gpup"
description="""
Need to ammend that last git commit and force push?

`git amender`

That's it. Thanks to `gpup` it guarantees that you'll never
accidentally force-push anywhere other than your `origin` repo.

Requires [gpup](https://github.com/masukomi/gpup)
"""
# usage_command=""
fallback_usage="""
USAGE: git amender
       adds changed files to last commit, and force pushes with gpup"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-amender"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["git"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
