# a template for `clu` toml files


# the name of the command or function you're documenting
name="git-log-deleted"
# a short (one line) description of what it does
short_description="runs git log for a file path that has been deleted"
description="""
I've needed the `git log` of a deleted file countless times. Sometimes
you want to know who deleted it. Sometimes why. Sometimes you need
something from that deleted file. The
command to do this requires 3 options and I can never remember it.

`git log-deleted path/to/where/the/file/was.txt`

Once you've got the log, you can then checkout any of the hashes
it shows you.

This is a simple wrapper around `git log` so if the file isn't found
you'll get a blank response, and a successful exit, because that's what git
log does for files it can't find.
"""
usage_command="git-log-deleted"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-log-deleted"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["git", "search"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
