# a template for `clu` toml files
# the name of the command or function you're documenting
name="git-branch-pr"
# a short (one line) description of what it does
short_description="Shows or opens the Pull Request (PR) for the current branch"
description="""
Want to easily open the GitHub Pull Request associated with a branch?

`git branch-pr -o`

`-o` tells it to open in your default browser, otherwise it'll just
output the link to the PR.


Requires: GitHub's [gh cli tool](https://cli.github.com/)
"""
usage_command="git-branch-pr -h"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-branch-pr"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["git", "github", "gh", "pr"]
# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
