# a template for `clu` toml files


# the name of the command or function you're documenting
name="git-url"
# a short (one line) description of what it does
short_description="generates an url to the specified file and/or commit in GitHub or GitLab"
description="""
This script has a _lot_ of options. The short version is that you
should use this when you need to share a link to a file, or a branch
in a GitHub repo.

You should also consider using this when you want a teammate to render
an opinion about a piece of code you're working on. Commit it. Push it
to GitHub, or GitLab and use this to generate a link they can use to
see it.
"""

usage_command="git-url -h"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-url"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=[ "git", "sharing" ]
asciicast_url="~/.local/share/tooloo/asciicasts/git-url.cast"

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
