# a template for `clu` toml files
# the name of the command or function you're documenting
name="git-oldest-ancestor"
# a short (one line) description of what it does
short_description="finds the oldest common ancestor between two git treeishes"
description="""
It's not easy to tell when one git branch diverged from another. Even
worse, it's not possible to give a difinitive response.

However, it _is_ possible to generate a response that's _probably_
right. That's what this script does. Give it two branches, the one you
believe to be the parent, and the one you believe to be the child, and
it'll make a good guess at the first common commit in their history.
That's the commit they _probably_ diverged at.
"""
usage_command="git-oldest-ancestor"
# fallback_usage="""
# USAGE: fallback_usage is used when
# usage_command is not present"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-oldest-ancestor"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["git", "search"]
# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
