# the name of the command or function you're documenting
name="git-conflicted"
# a short (one line) description of what it does
short_description="lists unmerged (confilcting) files"
description="""
A simple listing of all your un-merged files that have conflicts in
them.

(see also `git-add-conflicted`)
"""
# usage_command=""
fallback_usage="""
USAGE: git conflicted
       Lists unmerged (conflicting) files."""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-conflicted"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"
tags=["git", "merge"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
