# a template for `clu` toml files


# the name of the command or function you're documenting
name="git-add-conflicted"
# a short (one line) description of what it does
short_description="runs git add on any unmerged (conflicting) files"
description="""
After a git conflict you'll address the required changes and then
need to run `git add <path/to/conflicted/file>`.

This saves you time, by letting you just run `git add-conflicted`
in order to `add` all of them.
"""
#usage_command=""
fallback_usage="""
USAGE: git add-conflicted
       Adds any unmerged (conflicting) files to the index."""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="ttps://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-add-conflicted"
# where you can find the repo that contains this file
source_repo_url="ttps://github.com/masukomi/masuconfigs"
tags=["git", "merge"]

# [[cheats]]
# [[cheats.bar]]
# description = "a description of task bar with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
# [[cheats.baz]]
# description = "a description of task baz with backtrace_details"
# template="bar {{arg1}} {{arg2}}"
