# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="mayzeffer"
short_description="creates lines to add to raku-bootstrap"

description="""
part of the idempotent bootstrap process for raku
run mayzeffer to generate the lines that need to be added 
for a package you want to add to this process.
"""

# usage_command=""

fallback_usage="mayzeffer <package_name>"

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/.config/fish/functions/mayzeffer.fish"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs/"

# can this be included in exports like the static blog generation
exportable=false

tags=[ "raku", "cli", "yadm", "fish"  ]
