change-type:
    type: select
    destination: title
    after-string: ']'
    before-string: '['
    instructions: What kind of change?
    modifiable: true
    format: "%-12s"
    options:
        - fix
        - add
        - refactor
        - clean-up
breaking-indicator:
  type: select
  destination: title
  instructions: "Skip unless breaking change"
  allow-empty: true
  empty-selection-text: "Skip"
  after-string: ": "
  options:
    - breaking
commit-title:
    type: text
    destination: title
    placeholder: Commit Title
commit-description:
    allow-empty: true
    destination: body
    instructions: Please describe your changes.
    type: multiline-text
    after-string: "\n"
code-sections:
    type: multi-select
    record-as: joined-string
    allow-empty: true
    before-string: "\nCode Sections: "
    after-string: "\n"
    destination: body
    instructions: Which section(s) of the codebase?
    modifiable: true
    options:
        - core
        - docs
        - git
        - ui
        - ux
        - yaml
        - config
        - meta
        - tests
ticket-number:
    type: text
    destination: body
    data-type: integer
    allow-empty: true
    before-string: "\nTicket: "
    instructions: "Associated Ticket Number (if any)"
meta_element_changelog:
    display_aliases:
      fix: "fixed"
      add: "added"
      refactor: "refactored"
      clean-up: "cleaned"

