#!/usr/bin/env ruby
# frozen_string_literal: true

require 'set'

files = `git diff --cached --name-only --diff-filter=ACM`.split("\n")
tested_files = Set.new
# tracking tested files because there may be changes to
# foo.rb and foo_spec.rb which would result in
# foo_spec.rb being invoked twice.
def get_spec_filename(file)
  unless file.end_with? '_spec.rb'
    file = "spec/#{file.sub(%r{^app/}, '').sub(/\.rb$/, '_spec.rb')}"
  end
  file.sub(/engines\/\S+?\//, "")
end

files.each do |file|
  filename = file
  next unless file.end_with? '.rb'

  valid_code = system("ruby -c #{filename}")
  exit 2 unless valid_code

  filename = get_spec_filename(filename)
  $stderr.puts("XXX PWD: #{Dir.pwd} & FILENAME: #{filename}")
  next unless File.exist?(filename) && !tested_files.include?(filename)

  tested_files.add filename

  # normally....
  # response = system("bundle exec rspec #{filename}")
  response = system("/usr/local/bin/docker-compose exec -T api-server bin/bundle exec rspec #{filename}")
  unless response
    puts "spec failed: #{filename}"
    exit 1
  end
end
exit 0
